import type { Transaction } from "./useTransactionStore";

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: crypto.randomUUID(), description: 'Salário', amount: 5000, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Aluguel', amount: 1200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Supermercado', amount: 450, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Internet', amount: 100, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Academia', amount: 80, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Freelance', amount: 800, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Cinema', amount: 50, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Farmácia', amount: 120, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Restaurante', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Uber', amount: 30, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Venda de Livro', amount: 50, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Gasolina', amount: 250, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Netflix', amount: 40, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Spotify', amount: 30, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Presente', amount: 150, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Consultoria', amount: 1500, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Padaria', amount: 20, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Açougue', amount: 60, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Feira', amount: 80, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Dividendos', amount: 300, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Manutenção Carro', amount: 500, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Seguro de Vida', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Material Escolar', amount: 150, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Roupas', amount: 300, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Sapatos', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Reembolso', amount: 100, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Café', amount: 15, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Lanche', amount: 25, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Estacionamento', amount: 20, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Bônus', amount: 2000, type: 'income', date: new Date().toISOString() },
    { id: crypto.randomUUID(), description: 'Salário', amount: 5000, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Aluguel', amount: 1200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Supermercado', amount: 450, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Internet', amount: 100, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Academia', amount: 80, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Freelance', amount: 800, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Cinema', amount: 50, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Farmácia', amount: 120, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Restaurante', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Uber', amount: 30, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Venda de Livro', amount: 50, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Gasolina', amount: 250, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Netflix', amount: 40, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Spotify', amount: 30, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Presente', amount: 150, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Consultoria', amount: 1500, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Padaria', amount: 20, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Açougue', amount: 60, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Feira', amount: 80, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Dividendos', amount: 300, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Manutenção Carro', amount: 500, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Seguro de Vida', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Material Escolar', amount: 150, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Roupas', amount: 300, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Sapatos', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Reembolso', amount: 100, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Café', amount: 15, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Lanche', amount: 25, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Estacionamento', amount: 20, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Bônus', amount: 2000, type: 'income', date: new Date().toISOString() },
    { id: crypto.randomUUID(), description: 'Salário', amount: 5000, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Aluguel', amount: 1200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Supermercado', amount: 450, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Internet', amount: 100, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Academia', amount: 80, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Freelance', amount: 800, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Cinema', amount: 50, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Farmácia', amount: 120, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Restaurante', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Uber', amount: 30, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Venda de Livro', amount: 50, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Gasolina', amount: 250, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Netflix', amount: 40, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Spotify', amount: 30, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Presente', amount: 150, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Consultoria', amount: 1500, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Padaria', amount: 20, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Açougue', amount: 60, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Feira', amount: 80, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Dividendos', amount: 300, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Manutenção Carro', amount: 500, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Seguro de Vida', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Material Escolar', amount: 150, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Roupas', amount: 300, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Sapatos', amount: 200, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Reembolso', amount: 100, type: 'income', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Café', amount: 15, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Lanche', amount: 25, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Estacionamento', amount: 20, type: 'expense', date: new Date().toISOString() },
  { id: crypto.randomUUID(), description: 'Bônus', amount: 2000, type: 'income', date: new Date().toISOString() },
];